### ISSUE TITLE
Type declarations

### ISSUE THREAD

**Issue by jorgemasta** [haideralipunjabi/next-goatcounter#2]
I'm installing this package on my repo but I have realized that it doesn't have type declarations:
> Cannot find module 'goatcounter-nextjs' or its corresponding type declarations

Do you prefer to migrate it to TS or create a type declaration file?

**Comment by haideralipunjabi** [comment]
I am planning to migrate to Typescript soon. I published the typescript branch. Will test it soon and merge it with main.

**Comment by haideralipunjabi** [comment]
I have published `1.0.1` with Typescript.

**Comment by jorgemasta** [comment]
Yeah!

Thank you!!
