### ISSUE TITLE
Support for self-hosted instances?

### ISSUE THREAD

**Issue by mannp** [haideralipunjabi/next-goatcounter#8]
Hi there

Is it possible to configure for a self-hosted instance of goatcounter?

Thanks in advance.

Edit: Wonder is pasting part of my url ending 'count' will work....seems not :-/

`<script src="//gc.zgo.at/count.js" data-goatcounter="https://<selfhostedfqdn>/count" data-nscript="afterInteractive"></script>`

instead of

`<script data-goatcounter="https://<selfhostedfqdn>/count" async src="//<selfhostedfqdn>/count.js"></script>`

**Comment by haideralipunjabi** [comment]
As mentioned in the README, you can use the `scriptSrc` parameter to specify self hosted count.js location

**Comment by mannp** [comment]
> As mentioned in the README, you can use the `scriptSrc` parameter to specify self hosted count.js location

Okay.
